; Wav to .h 
; Alex BOTZUNG - Juillet 2015
; Assume que le fichier est un .wav 8bit MONO

FichierWAV$ = OpenFileRequester("Ouvre un WAV 8bit MONO...","","Fichier WAV|*.wav",0)

If FichierWAV$ = ""
  MessageRequester("Erreur", "Pas de fichier...") : End
EndIf

FichierH$ = SaveFileRequester("Sauve ton fichier .h ...", "sounddata.h","Fichier .h|*.h", 0)

If FichierH$ = ""
  MessageRequester("Erreur", "Pas de fichier...") : End
EndIf


; L'entête d'un fichier WAV à une longueur (dans un cadre excellent) de 44 octets
; donc on commencera la conversion à [ENTETE] +1 jusqu'à EOF

MonBuffer = 0
NbrValeur.q = 0
NbrTableau = 1
BufferDesValeurs$ = ""

If ReadFile(1, FichierWAV$)
  If Lof(1)>30000
    MessageRequester("Erreur!", "Le fichier WAV doit être plus PETIT que 30Ko !", #MB_ICONERROR)
    CloseFile(1)
    End
  EndIf
  
  Prefixe$ = InputRequester("WAV2H", "Préfixe des variables ? Defaut: sounddata", "sounddata")
  
  If CreateFile(2, FichierH$)
    FileSeek(1, 44)  ;  44 = Taille du HEADER WAV   
    WriteStringN(2, "// Sounddata generated by Wav2C - Alex BOTZUNG") 
    WriteStringN(2, "// Original Filename : "+GetFilePart(FichierWAV$))
    ;WriteStringN(2, "int dummydummy = 0;")
    
    While Not Eof(1)
      MonBuffer = ReadAsciiCharacter(1)
      ;WriteByte(2, MonBuffer) 
      BufferDesValeurs$ = BufferDesValeurs$ + StrU(MonBuffer, #PB_Ascii) + ", "
      NbrValeur + 1
      ;If Mod(NbrValeur, 500)=0 And NbrValeur > 0
      ;  WriteStringN(2, "const unsigned char sounddata_data[] PROGMEM = {" + BufferDesValeurs$ + "};")
      ;  NbrTableau + 1
      ;  BufferDesValeurs$ = ""
      ;EndIf
      
    Wend  
    
    WriteStringN(2, "const unsigned long "+Prefixe$+"_length=" + Str(NbrValeur) + ";")
    WriteStringN(2, "const unsigned char "+Prefixe$+"_data[] PROGMEM = {" + BufferDesValeurs$ + "};")
    
    ;For x=1 To NbrTableau
    ;  WriteStringN(2, "dummydummy = sounddata" + Str(x) + "_data[0];")
    ;Next x
    
    ;WriteStringN(2, "const unsigned char sounddata_data[] PROGMEM = {" + BufferDesValeurs$ + "};")
    
    
  Else 
    MessageRequester("Erreur", "Impossible d'ouvrir le fichier CIBLE... (RW+)") : End
  EndIf
Else
  MessageRequester("Erreur", "Impossible d'ouvrir le fichier SOURCE... (R)") : End
EndIf

CloseFile(1)
CloseFile(2)

MessageRequester("OK", "Conversion OK!")
